In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import tensorflow
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2)


In [5]:
X_train

age  affordibility
15   55              1
13   29              0
23   45              1
0    22              1
6    55              0
25   54              1
11   28              1
1    25              0
7    60              0
16   25              0
20   21              1
5    56              1
26   23              1
21   26              0
24   50              1
14   49              1
27   46              1
22   40              1
8    62              1
3    52              0
2    47              1
18   19              0

In [6]:
X_train_scaled=X_train.copy()
X_test_scaled=X_test.copy()

## Scalling Data

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
X_train_scaled['age']=scaler.fit_transform(X_train_scaled['age'].values.reshape(-1,1))

X_test_scaled['age']=scaler.fit_transform(X_test['age'].values.reshape(-1,1))



In [8]:
model=keras.Sequential(
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
)
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [9]:
model.fit(X_train_scaled,y_train,epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 712ms/step - loss: 0.6903 - accuracy: 0.5455
Epoch 2/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6899 - accuracy: 0.5455
Epoch 3/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6895 - accuracy: 0.5455
Epoch 4/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6891 - accuracy: 0.5455
Epoch 5/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6888 - accuracy: 0.5455
Epoch 6/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.6884 - accuracy: 0.5455
Epoch 7/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6880 - accuracy: 0.5455
Epoch 8/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6876 - accuracy: 0.5455
Epoch 9/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6872 - accuracy: 0.5455
Epoch 10/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6868 - accuracy: 0.5455
Epoch 11/1000
1

In [10]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 126ms/step - loss: 0.4289 - accuracy: 1.0000


[0.42889007925987244, 1.0]

In [12]:
model.predict(X_test_scaled)

array([[0.6855231 ],
       [0.768615  ],
       [0.39335257],
       [0.44927222],
       [0.78681225],
       [0.44927222]], dtype=float32)

In [13]:
model.predict(X_test_scaled)

array([[0.6855231 ],
       [0.768615  ],
       [0.39335257],
       [0.44927222],
       [0.78681225],
       [0.44927222]], dtype=float32)

In [14]:
coef,intercept=model.get_weights()

In [15]:
coef,intercept

(array([[1.5094278],
        [0.5455565]], dtype=float32), array([-0.7491682], dtype=float32))

# Building Neural Network from Scratch


In [18]:
def sigmoid(X):
  return 1/(1-np.exp(-X))

sigmoid(22)

1.0000000002789469

In [19]:
def prediction(age,affordibility):
  weighted_sum=coef[0]*age+coef[1]*affordibility+intercept[0]
  return sigmoid(weighted_sum)

In [20]:
prediction(X_test_scaled['age'].values[0],X_test_scaled['affordibility'].values[0])

array([1.8475413], dtype=float32)

In [21]:
def log_loss(y_true,y_pred):
  epsilon=1e-15
  y_pred_new=[max(i,epsilon) for i in y_pred]  
  y_pred_new=[max(i,1-epsilon) for i in y_pred_new]
  y_pred_new=np.array(y_pred_new)
  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [22]:
def gradient_descent(age,affordibility,y_true,epochs):
  w1=w2=1
  b=0
  rate=0.5
  n=len(age)

  for i in range(epochs):
    weighted_sum=w1*age+w2*affordibility+b

    # print(weighted_sum)
    y_pred=sigmoid(weighted_sum)
    # print(y_pred)
    loss=log_loss(y_true,y_pred)

    w1d=(1/n)*np.dot(np.transpose(age),(y_pred-y_true))
    w2d=(1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
    bd=np.mean(y_pred-y_true)
    
    w1=w1-rate*w1d
    w2=w2-rate*w2d
    b=b-rate*bd

    # print(f'Epochs{i}, w1:{w1} , w2:{w2}, loss:{loss}')
    # return w1,w2,b

In [23]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in log
  


In [29]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

In [30]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [31]:

customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)


Epoch:0, w1:0.978744319704988, w2:0.9434249936409371, bias:-0.11954777870867002, loss:17.26978799617044
Epoch:50, w1:1.8734097846147362, w2:0.9689463825663734, bias:-1.442596707176429, loss:17.26978799617044
Epoch:100, w1:2.6137721631016686, w2:1.153544585637519, bias:-1.9799642120100869, loss:17.26978799617044
Epoch:150, w1:3.122113237162877, w2:1.2799220457054796, bias:-2.3513847246857766, loss:17.26978799617044
Epoch:200, w1:3.486212992274062, w2:1.3778717267730318, bias:-2.624929017942413, loss:17.26978799617044
Epoch:250, w1:3.7560610719430145, w2:1.4574033293556536, bias:-2.8341329140184266, loss:17.26978799617044
Epoch:300, w1:3.961554138205251, w2:1.523043470004862, bias:-2.9980558214293684, loss:17.26978799617044
Epoch:350, w1:4.121423239397255, w2:1.5775316179307337, bias:-3.1286581825624133, loss:17.26978799617044
Epoch:400, w1:4.24790899531574, w2:1.6228670052478613, bias:-3.2339794782257165, loss:17.26978799617044
Epoch:450, w1:4.349317142837304, w2:1.6606374345364874, bia

In [32]:

customModel.predict(X_test_scaled)


4     0.779221
17    0.931536
12    0.061090
19    0.131536
9     0.950163
10    0.131536
dtype: float64